import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outDir = "/Users/mac/computerscience/0做完了/15会计研究/v4/lit_review";
const outputPath = `${outDir}/个人破产制度文献综述_v1.xlsx`;

const headers = [
  "年份",
  "APA格式的引用",
  "文献类别",
  "X",
  "自然人责任/暴露测度",
  "Y",
  "M",
  "模型",
  "研究问题",
  "摘要",
  "与本题关系",
  "撞题判断",
  "下一步用途/备注",
];

const rows = [
  [
    "2026",
    "陈怡欣、张俊瑞（2026）。个人破产制度与企业盈余平滑——基于中国个人破产试点的准自然实验。《会计研究》，2026年第2期。",
    "中国个人破产-会计Y",
    "中级人民法院建立个人破产制度/个人债务清理试点。",
    "主要是城市层面PB；机制偏员工财务忧虑。",
    "盈余平滑；进一步分析股价崩盘风险。",
    "员工财务忧虑；机会主义属性盈余平滑。",
    "多期DID；平行趋势；异质性；经济后果检验。",
    "个人破产制度是否影响企业盈余平滑及资本市场后果。",
    "发现个人破产制度显著降低盈余平滑，机制来自员工财务忧虑缓解；进一步发现制度减少机会主义属性盈余平滑并缓解股价崩盘风险。",
    "最强相邻文献，说明PB与崩盘风险连接是对的，但PB->崩盘风险不能作为裸主张。",
    "强相邻；不能简单复刻。",
    "必须区别为PB x自然人责任暴露、控制人失败成本、坏消息隐藏，而不是员工忧虑和盈余平滑。来源：本地PDF、西北大学新闻、中国会计学会目录。",
  ],
  [
    "2025/2026",
    "纪翔阁等（2025/2026）。个人破产制度与信贷资源供给。《金融研究》。",
    "中国个人破产-银行供给",
    "城市层面个人破产试点。",
    "银行所在地/城市政策；不是企业自然人暴露。",
    "城市商业银行贷款供给、贷款类型、期限和担保结构。",
    "银行风险态度；机会主义债务人担忧；信贷收缩。",
    "DID主模型；IV为稳健性。",
    "个人破产制度是否影响银行信贷资源供给。",
    "发现个人破产制度降低银行信贷供给，并改变抵押、担保和长期贷款结构。",
    "为我们B线债务短期化提供机制基础；也提示负面政策叙事风险。",
    "相邻但不同。",
    "若写崩盘风险，可用作竞争机制：信贷收缩可能提高高杠杆企业风险。来源：金融研究官网与本地PDF。",
  ],
  [
    "2025/2026",
    "汤旭东等。个人破产试点促进城市科技创业活跃度提升。",
    "中国个人破产-创业活跃度",
    "城市个人破产/个人债务集中清理试点。",
    "城市层面制度冲击。",
    "城市科技创业活跃度。",
    "恐惧失败下降；融资环境；营商环境。",
    "渐进DID。",
    "个人破产试点是否促进城市层面科技创业。",
    "把个人破产制度解释为失败容错和创业再出发的制度安排。",
    "支持我们把PB解释为失败成本下降；但它是城市创业层面，不是企业信息风险。",
    "相邻但层级不同。",
    "可放在制度背景和失败容错文献中。来源：本地PDF。",
  ],
  [
    "2025",
    "Xu, X., & Xu, B. (2025). The inhibitory effect of personal bankruptcy laws on household debt: Evidence from a pilot program. Finance Research Letters, 81, 107533. https://doi.org/10.1016/j.frl.2025.107533",
    "中国个人破产-家庭金融",
    "中国个人破产试点。",
    "家庭/城市层面暴露。",
    "家庭债务增长。",
    "债务重整预期；消费金融约束。",
    "DID；中国调查数据。",
    "个人破产试点是否抑制家庭债务螺旋增长。",
    "基于2015-2023年中国家庭调查，发现个人破产法有效抑制家庭债务螺旋增长。",
    "说明个人破产在中国已有家庭金融后果研究；不是企业会计，但可做制度经济后果背景。",
    "相邻但不撞。",
    "可用于中国制度背景；需正式下载核对全文。",
  ],
  [
    "2020",
    "Chen, Y.-W., Halford, J. T., Hsu, H.-C., & Lin, C.-B. (2020). Personal bankruptcy laws and corporate policies. Journal of Financial and Quantitative Analysis, 55(7), 2397-2428. https://doi.org/10.1017/S0022109019000620",
    "个人破产-公司政策",
    "2005年BAPCPA限制个人破产保护。",
    "员工预期个人财富冲击；受员工影响更大的公司。",
    "劳动成本、投资、风险承担。",
    "员工财富风险；员工议价能力。",
    "准自然实验；企业政策回归。",
    "个人破产法变化是否通过员工个人财富风险影响公司政策。",
    "个人破产保护收紧后，受影响企业提高劳动成本、减少投资并降低风险承担，员工议价能力越强效应越明显。",
    "是把个人破产法和公司政策连接起来的英文核心文献。",
    "机制相邻，不撞。",
    "可借其“个人法制度也会影响公司政策”的理论合法性。",
  ],
  [
    "2024",
    "Halford, J. T., Hayes, R. M., & Sibilkov, V. (2024). Personal bankruptcy costs, union bargaining power, and capital structure. Journal of Banking & Finance, 168, 107271. https://doi.org/10.1016/j.jbankfin.2024.107271",
    "个人破产-资本结构",
    "BAPCPA提高个人破产成本。",
    "工会化企业/员工个人破产成本暴露。",
    "企业杠杆和劳动成本。",
    "工会议价能力。",
    "DID与DDD。",
    "个人破产成本是否通过劳动力议价影响企业资本结构。",
    "发现个人破产成本上升削弱工会议价能力，工会化企业相对降低杠杆。",
    "说明个人破产成本可通过自然人主体进入企业财务政策。",
    "相邻但不撞。",
    "可借DDD设计和暴露交互写法。",
  ],
  [
    "1997",
    "Gropp, R., Scholz, J. K., & White, M. J. (1997). Personal bankruptcy and credit supply and demand. The Quarterly Journal of Economics, 112(1), 217-251. https://doi.org/10.1162/003355397555172",
    "个人破产-信贷供需",
    "美国州层面个人破产豁免额度。",
    "资产水平；高/低资产借款人。",
    "信贷可得性、信贷持有、汽车贷款利率。",
    "债权人保护与财富再分配。",
    "家庭调查数据；州法差异。",
    "个人破产豁免如何影响信贷供给和需求。",
    "宽松豁免提升高资产家庭信贷持有，但降低低资产家庭信贷可得性并提高利率。",
    "为信贷收缩/信用重新定价机制提供基础。",
    "基础文献。",
    "可用来解释PB可能削弱债权追偿价值并改变贷款条件。",
  ],
  [
    "2003",
    "Fan, W., & White, M. J. (2003). Personal bankruptcy and the level of entrepreneurial activity. Journal of Law and Economics, 46(2), 543-567. https://doi.org/10.1086/382602",
    "个人破产-创业",
    "美国州层面个人破产豁免水平。",
    "非公司制企业主个人债务和个人资产保护。",
    "家庭拥有企业的概率。",
    "财富保险；风险厌恶；创业失败成本。",
    "理论模型和家庭微观数据检验。",
    "更高个人破产豁免是否鼓励创业。",
    "发现无限豁免州家庭拥有企业的概率显著更高，支持个人财富保险促进创业。",
    "失败容错机制的经典文献。",
    "基础文献。",
    "可支撑自然人控制人失败成本下降的理论。",
  ],
  [
    "2007",
    "Lee, S.-H., Peng, M. W., & Barney, J. B. (2007). Bankruptcy law and entrepreneurship development: A real options perspective. Academy of Management Review, 32(1), 257-272. https://doi.org/10.5465/AMR.2007.23464070",
    "个人破产-管理学理论",
    "创业友好型破产法。",
    "失败惩罚、污名和创业者选择权。",
    "创业发展。",
    "真实期权；风险承担；失败污名。",
    "理论论文。",
    "为什么破产法会影响高风险创业选择。",
    "提出更友好的破产法可鼓励创业者抓住高风险高回报机会。",
    "管理学理论支撑强。",
    "基础理论。",
    "可借“失败惩罚过重导致高价值机会放弃”的写法。",
  ],
  [
    "2008",
    "Armour, J., & Cumming, D. (2008). Bankruptcy law and entrepreneurship. American Law and Economics Review, 10(2), 303-350.",
    "个人破产-跨国创业",
    "15国1990-2005年个人破产法宽容度指数。",
    "破产后免责期限等制度宽容度。",
    "自雇率。",
    "宽容失败；创业进入。",
    "跨国面板回归。",
    "更宽容的个人破产法是否促进创业。",
    "构造个人破产法宽容度指数，发现更创业友好的破产法显著提高自雇率。",
    "说明个人破产制度可作为企业家失败成本冲击。",
    "基础文献。",
    "可放在失败容错制度文献。",
  ],
  [
    "2014",
    "Fossen, F. M. (2014). Personal bankruptcy law, wealth, and entrepreneurship—Evidence from the introduction of a 'fresh start' policy. American Law and Economics Review, 16(1), 269-312.",
    "个人破产-德国准实验",
    "德国1999年fresh start政策。",
    "个人财富水平；低财富创业者。",
    "进入创业。",
    "保险效应 vs 利率效应。",
    "准自然实验；家庭面板。",
    "fresh start政策对创业的影响是否因财富不同而异。",
    "发现更宽松个人破产制度的保险效应超过利率效应，尤其鼓励低财富个体创业。",
    "直接支持失败成本下降机制。",
    "基础/相邻。",
    "可借“保险效应与信贷成本效应并存”的双机制。",
  ],
  [
    "2015",
    "Mankart, J., & Rodano, G. (2015). Personal bankruptcy law, debt portfolios, and entrepreneurship. Journal of Monetary Economics, 76, 157-172. https://doi.org/10.1016/j.jmoneco.2015.09.001",
    "个人破产-创业与信贷",
    "个人破产制度宽严。",
    "有担保/无担保信贷组合。",
    "创业、违约、福利。",
    "失败保险 vs 信贷条件恶化。",
    "量化一般均衡模型。",
    "个人破产制度如何在创业保险和信贷收缩之间权衡。",
    "强调有担保信贷对个人破产制度效果的重要性，指出破产提供失败保险但会恶化信用条件。",
    "非常适合支撑我们“失败容错 vs 信贷收缩”的双机制。",
    "基础/机制文献。",
    "应重点引用。",
  ],
  [
    "2017",
    "Cerqueiro, G., & Penas, M. F. (2017). How does personal bankruptcy law affect startups? Review of Financial Studies, 30(7), 2523-2554.",
    "个人破产-startup",
    "个人破产法差异。",
    "创业企业和创业者个人资产保护。",
    "创业进入、企业质量、融资。",
    "失败保险与信贷约束。",
    "实证研究。",
    "个人破产法如何影响初创企业。",
    "研究个人破产法律对创业活动和初创企业融资/质量的影响。",
    "有助于把制度冲击从城市创业扩展到企业微观行为。",
    "相邻。",
    "需补全文核对具体结果。",
  ],
  [
    "2006",
    "Jin, L., & Myers, S. C. (2006). R2 around the world: New theory and new tests. Journal of Financial Economics, 79(2), 257-292.",
    "崩盘风险基础理论",
    "信息不透明和投资者保护。",
    "经理人吸收/隐藏公司特定信息。",
    "股价同步性与极端收益风险。",
    "信息不透明；坏消息隐藏。",
    "理论与跨国实证。",
    "为什么信息不透明会导致公司特定坏消息积累。",
    "提出公司透明度低时内部人吸收公司特定风险，坏消息积累后释放导致极端下跌。",
    "坏消息隐藏理论源头。",
    "基础文献。",
    "需作为崩盘风险理论起点。",
  ],
  [
    "2009",
    "Hutton, A. P., Marcus, A. J., & Tehranian, H. (2009). Opaque financial reports, R2, and crash risk. Journal of Financial Economics, 94(1), 67-86. https://doi.org/10.1016/j.jfineco.2008.10.003",
    "崩盘风险-会计不透明",
    "财务报告不透明度/盈余管理。",
    "企业信息透明度。",
    "R2和股价崩盘风险。",
    "坏消息隐藏。",
    "美国上市公司面板回归。",
    "财务报告不透明是否提高崩盘风险。",
    "发现财务报告越不透明，股价同步性和崩盘风险越高。",
    "支持以NCSKEW/DUVOL衡量坏消息隐藏后果。",
    "基础文献。",
    "必须引用。",
  ],
  [
    "2011",
    "Kim, J.-B., Li, Y., & Zhang, L. (2011). Corporate tax avoidance and stock price crash risk: Firm-level analysis. Journal of Financial Economics, 100(3), 639-662. https://doi.org/10.1016/j.jfineco.2010.07.007",
    "崩盘风险-代理问题",
    "企业避税。",
    "经理人机会主义和信息遮掩工具。",
    "股价崩盘风险。",
    "租金攫取；坏消息隐藏。",
    "公司面板回归。",
    "避税是否提高未来崩盘风险。",
    "发现避税与崩盘风险正相关，且外部监督能缓解该关系。",
    "提供“坏消息隐藏->崩盘风险”的经典代理问题证据。",
    "基础文献。",
    "可借机制语言。",
  ],
  [
    "2013",
    "Callen, J. L., & Fang, X. (2013). Institutional investor stability and crash risk: Monitoring versus short-termism? Journal of Banking & Finance, 37(8), 3047-3063.",
    "崩盘风险-外部监督",
    "机构投资者稳定性。",
    "长期监督 vs 短期交易压力。",
    "未来股价崩盘风险。",
    "监督约束坏消息隐藏；短期主义增加压力。",
    "美国上市公司面板。",
    "机构投资者稳定性如何影响崩盘风险。",
    "长期稳定机构投资者降低崩盘风险，短期机构可能相反。",
    "有助于写外部监督异质性。",
    "基础/机制。",
    "可用于异质性：机构持股少/外部监督弱时PB效应更强。",
  ],
  [
    "2016",
    "Kim, J.-B., Wang, Z., & Zhang, L. (2016). CEO overconfidence and stock price crash risk. Contemporary Accounting Research, 33(4), 1720-1749. https://doi.org/10.1111/1911-3846.12217",
    "崩盘风险-管理者心理",
    "CEO过度自信。",
    "管理者对坏项目和负面反馈的认知偏差。",
    "未来股价崩盘风险。",
    "过度投资；坏消息解释/拖延。",
    "美国上市公司面板。",
    "过度自信CEO是否更可能导致崩盘风险。",
    "发现过度自信CEO更可能保留负NPV项目并积累坏消息，从而提高崩盘风险；会计稳健性可缓解。",
    "与我们控制人失败成本/赌下一期翻盘逻辑高度相关。",
    "基础机制。",
    "可用来写自然人控制人强撑风险的动机。",
  ],
  [
    "2020",
    "Deng, X., Gao, L., & Kim, J.-B. (2020). Short-sale constraints and stock price crash risk: Causal evidence from a natural experiment. Journal of Corporate Finance, 60, 101498. https://doi.org/10.1016/j.jcorpfin.2019.101498",
    "崩盘风险-监管冲击",
    "Regulation SHO下卖空约束解除。",
    "市场监督强度。",
    "股价崩盘风险。",
    "卖空者监督；披露策略；投资效率。",
    "DID自然实验。",
    "卖空约束解除是否降低崩盘风险。",
    "发现卖空约束解除降低崩盘风险，机制是约束管理层坏消息隐藏并改善投资效率。",
    "提供监管冲击->坏消息隐藏->崩盘风险的写法模板。",
    "方法相邻。",
    "可借事件研究和机制检验风格。",
  ],
  [
    "2021",
    "Li, D., Xing, L., & Zhao, Y. (2021). Does extended auditor disclosure deter managerial bad-news hoarding? Evidence from crash risk. Journal of Business Finance & Accounting.",
    "崩盘风险-审计披露",
    "英国扩展审计报告制度。",
    "被强制披露关键风险的企业。",
    "股价崩盘风险。",
    "审计风险披露；坏消息隐藏。",
    "准自然实验。",
    "扩展审计报告是否抑制管理层坏消息隐藏。",
    "发现扩展审计报告采用降低崩盘风险，尤其与收入确认重大错报风险披露有关。",
    "说明制度披露/外部审计可通过坏消息隐藏影响崩盘风险。",
    "方法相邻。",
    "可用于审计机制但不是当前主线。",
  ],
  [
    "2021",
    "Zhang, X., Ma, L., & Wang, Y. (2021). Controlling shareholder share pledging and stock price crash risk: Evidence from China. International Review of Financial Analysis, 78, 101839. https://doi.org/10.1016/j.irfa.2021.101839",
    "中国崩盘风险-控制人",
    "控股股东股权质押。",
    "控制人财富压力和坏消息隐藏收益/成本。",
    "股价崩盘风险。",
    "控制人坏消息隐藏；内部控制；媒体监督。",
    "中国上市公司面板。",
    "控制人股权质押是否提高崩盘风险。",
    "发现控股股东质押期间企业未来崩盘风险更高，机制与内部人坏消息隐藏有关。",
    "与自然人控制人失败成本暴露高度相关。",
    "重要相邻。",
    "可用作异质性/竞争机制：股权质押压力高时PB效应如何变化。",
  ],
  [
    "2024",
    "Yin, A., Han, L., & Shen, Y. (2024). Unravelling the enigma: managerial bad news hoarding and financial analyst forecasts. Review of Quantitative Finance and Accounting. https://doi.org/10.1007/s11156-024-01370-5",
    "崩盘风险-分析师",
    "管理层坏消息隐藏，使用崩盘风险代理。",
    "分析师信息环境。",
    "预测准确度和分歧。",
    "羊群行为；锚定效应。",
    "美国上市公司面板。",
    "坏消息隐藏如何影响分析师预测质量。",
    "使用崩盘风险衡量坏消息隐藏，并考察其对分析师预测的影响。",
    "说明崩盘风险已被广泛用作坏消息隐藏代理。",
    "背景文献。",
    "可用于Y解释和机制引用。",
  ],
  [
    "2024",
    "Bhojraj, S., Dantas, M., Gao, G., Piao, J., & Silva, F. B. G. (2025). The nature of stock price crash risk: Hoarding of bad news or non-agency uncertainty? Working paper.",
    "崩盘风险-测度争议",
    "股价崩盘风险本身。",
    "区分坏消息隐藏与非代理不确定性。",
    "崩盘风险解释。",
    "代理问题 vs 基础风险暴露。",
    "多重识别测试。",
    "崩盘风险到底是否总是坏消息隐藏。",
    "重新检验崩盘风险文献的坏消息隐藏假说，提醒研究者区分代理性隐藏和基本面不确定性。",
    "对我们是重要警告：需要机制证据证明不是基本面风险。",
    "风险提示文献。",
    "可在稳健性中控制基本面风险、现金流波动、行业冲击。",
  ],
  [
    "2026",
    "当前项目试跑（2026）。个人破产制度候选Y全量重跑。Local pilot report.",
    "本项目试跑",
    "中国个人破产/个债清理试点 narrow政策表。",
    "natural_pre、failure_cost_pre、high_lev_pre等政策前暴露。",
    "NCSKEW、DUVOL、short_liab_ratio、AuditFee、InvestIneff等。",
    "失败容错 vs 信贷收缩。",
    "暴露型DID/DDD；企业FE、城市年份FE、行业年份FE；事件研究。",
    "哪些Y能跑出来且不撞题。",
    "自然人控制和失败成本暴露下崩盘风险下降且前趋势较好；高杠杆下崩盘风险上升；债务短期化稳健；审计和投资效率不稳。",
    "为文献综述后的选题选择提供本地证据。",
    "内部证据。",
    "文件：pb_all_candidates_rerun_report.md、pb_crash_novelty_search.md。",
  ],
];

function csvEscape(value) {
  if (value === null || value === undefined) return "";
  const s = String(value);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

const csv = [headers, ...rows].map((row) => row.map(csvEscape).join(",")).join("\n");
const workbook = await Workbook.fromCSV(csv, { sheetName: "文献综述" });

await fs.mkdir(outDir, { recursive: true });

const check = await workbook.inspect({
  kind: "table",
  range: "文献综述!A1:M8",
  include: "values",
  tableMaxRows: 8,
  tableMaxCols: 13,
});
console.log(check.ndjson);

const errors = await workbook.inspect({
  kind: "match",
  searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",
  options: { useRegex: true, maxResults: 50 },
  summary: "formula error scan",
});
console.log(errors.ndjson);

await workbook.render({ sheetName: "文献综述", range: "A1:M18", scale: 1 });
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outputPath);
console.log(outputPath);
